# -*- coding: utf-8 -*-
"""
@author: Chenglong Chen <c.chenglong@gmail.com>
@brief: one feature conf

Generated by
python get_feature_conf_nonlinear.py -d 5 -o feature_conf_nonlinear_201604170111.py

Format:
FEATURE_NAME : (MANDATORY, TRANSFORM)

"""

import config
from feature_transformer import SimpleTransform, ColumnSelector

LSA_COLUMNS = range(5)

feature_dict = {

"AttrBulletCount_product_attribute_list_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"AttrBulletRatio_product_attribute_list_1D" : (False, SimpleTransform()),
"AttrCount_product_attribute_list_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"AttrHasIndoorOutdoor_product_attribute_list_1D" : (False, SimpleTransform()),
"AttrHasProductDepth_product_attribute_list_1D" : (False, SimpleTransform()),
"AttrHasProductHeight_product_attribute_list_1D" : (False, SimpleTransform()),
"AttrHasProductLength_product_attribute_list_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"AttrHasProductWidth_product_attribute_list_1D" : (False, SimpleTransform()),
"AttrNonBulletCount_product_attribute_list_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"AttrNonBulletRatio_product_attribute_list_1D" : (False, SimpleTransform()),
"CharDistribution_CosineSim_search_term_x_product_attribute_1D" : (False, SimpleTransform()),
"CharDistribution_CosineSim_search_term_x_product_description_1D" : (False, SimpleTransform()),
"CharDistribution_CosineSim_search_term_x_product_title_1D" : (False, SimpleTransform()),
"CharDistribution_KL_search_term_x_product_attribute_1D" : (False, SimpleTransform()),
"CharDistribution_KL_search_term_x_product_description_1D" : (False, SimpleTransform()),
"CharDistribution_KL_search_term_x_product_title_1D" : (False, SimpleTransform()),
"CooccurrenceCount_Bigram_product_attribute_x_search_term_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Bigram_product_brand_x_search_term_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Bigram_product_color_x_search_term_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Bigram_product_description_x_search_term_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Bigram_product_title_product_name_x_search_term_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Bigram_product_title_x_search_term_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Bigram_search_term_x_product_attribute_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Bigram_search_term_x_product_description_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Bigram_search_term_x_product_title_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Bigram_search_term_x_product_title_product_name_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Trigram_product_attribute_x_search_term_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Trigram_product_brand_x_search_term_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Trigram_product_color_x_search_term_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Trigram_product_description_x_search_term_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Trigram_product_title_product_name_x_search_term_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Trigram_product_title_x_search_term_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Trigram_search_term_x_product_attribute_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Trigram_search_term_x_product_description_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"CooccurrenceCount_Trigram_search_term_x_product_title_1D" : (False, SimpleTransform(config.COUNT_TRANSFORM)),
"Co